language: python
python:
  - "2.7"

sudo: false
cache:
  directories:
     - "~/.platformio"

install:
  - pip install -U platformio

script:
  - platformio run -e uno

env:
  PLATFORMIO_BUILD_FLAGS="-DTRANSMITTER"
  PLATFORMIO_BUILD_FLAGS="-DRECEIVER"
